const $=id=>document.getElementById(id);let start=0,one=false,present=false,selected=new Set(),bank=[];
function option(el,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;el.append(o)}
for(let u=1;u<=5;u++){const group=document.createElement('optgroup');group.label='Unit '+u;CONTENT.forEach((t,i)=>{if(t.unit===u)option(group,i,t.code+' — '+t.title)});$('topic').append(group)}CATEGORIES.forEach(c=>option($('category'),c,c));
function makeBank(){if($('kind').value==='wild')return [{frame:Wild.draft.text,tag:'Wild card',image:Wild.draft.image,alt:Wild.draft.alt}];const generic=$('kind').value==='generic',source=generic?GENERAL:CONTENT[+$('topic').value].frames;const categories=$('category').value==='all'?CATEGORIES:[$('category').value];const items=[];const depth=Math.max(...categories.map(c=>source[c].length));for(let i=0;i<depth;i++)for(const tag of categories){if(source[tag][i])items.push({frame:source[tag][i],tag})}return items;}
function textWithBlanks(el,text){text.split('___').forEach((part,j)=>{if(j){const b=document.createElement('span');b.className='blank';b.textContent='___';el.append(b)}el.append(document.createTextNode(part))})}
function render(){const generic=$('kind').value==='generic',t=CONTENT[+$('topic').value];bank=makeBank();const wild=$('kind').value==='wild';$('topicControl').hidden=generic||wild;$('categoryControl').hidden=wild;$('wildEditor').hidden=!wild;$('count').hidden=wild;$('clear').hidden=wild;$('selectionStatus').hidden=wild;$('project').disabled=wild&&!Wild.draft.text.trim()&&!Wild.draft.image;$('title').textContent=wild?(Wild.draft.title||'Wild card'):generic?'General sentence starters':t.code+' · '+t.title;$('meta').hidden=wild;$('meta').textContent=(generic?'Any mathematical topic':'Unit '+t.unit)+( $('category').value==='all'?' · All categories':' · '+$('category').value);$('frames').replaceChildren();const indices=present&&selected.size?[...selected]:(Array.from({length:Math.min(present?(one?1:3):6,bank.length)},(_,i)=>(start+i)%bank.length));indices.forEach((idx,i)=>{const item=bank[idx],row=document.createElement('article');row.className='frame'+(selected.has(idx)?' selected':'');const n=document.createElement('span');n.className='number';n.textContent=String(i+1).padStart(2,'0');n.setAttribute('aria-hidden','true');const content=document.createElement('div');content.className='content';const tag=document.createElement('div');tag.className='tag';tag.textContent=item.tag;const f=document.createElement('p');f.className='sentence';textWithBlanks(f,item.frame);content.append(tag,f);if(item.image){const img=document.createElement('img');img.className='wild-card-image';img.src=item.image;img.alt=item.alt||'Instructor-provided image';content.append(img);row.classList.add('wild-frame')}const pick=document.createElement('button');pick.className='pick';pick.hidden=wild;pick.textContent=selected.has(idx)?'Selected':'Select';pick.setAttribute('aria-pressed',String(selected.has(idx)));pick.setAttribute('aria-label',(selected.has(idx)?'Deselect':'Select')+' frame '+(i+1));pick.onclick=()=>{if(selected.has(idx))selected.delete(idx);else if(selected.size<3)selected.add(idx);else{$('selectionStatus').textContent='Three selected. Deselect one to choose another.';return}render()};row.append(n,content,pick);$('frames').append(row)});$('selectionStatus').textContent=selected.size?selected.size+' selected for the board.':'Choose up to three frames, or present the first '+(one?'one.':'three.');$('count').textContent=one?'Show three frames':'Show one frame';$('more').hidden=(present&&selected.size>0)||bank.length<=indices.length;document.body.classList.toggle('one',present&&(selected.size?selected.size===1:one));}
function reset(){start=0;selected.clear();render()}
$('topic').onchange=$('kind').onchange=$('category').onchange=reset;$('size').onchange=()=>document.body.style.setProperty('--scale',$('size').value);$('count').onclick=()=>{one=!one;render()};$('clear').onclick=()=>{selected.clear();render()};$('more').onclick=()=>{start=(start+(present?(one?1:3):6))%bank.length;render()};
function presentation(value){present=value;document.body.classList.toggle('present',value);$('exit').hidden=!value;render();if(value)$('exit').focus();else $('project').focus();window.scrollTo(0,0)}
$('project').onclick=()=>presentation(true);$('exit').onclick=()=>presentation(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&present)presentation(false);if(e.key==='ArrowRight'&&present&&!selected.size){e.preventDefault();$('more').click()}});render();

const ROUTINES={
think:{title:'Think–Pair–Share',steps:['Think: Prepare an idea independently using a sentence frame.','Pair: Take turns explaining your reasoning and listening to your partner.','Share: Be ready to contribute an idea or question from your conversation.']},
talk:{title:'Turn & Talk',steps:['Turn to a partner. Each person shares one idea using a sentence frame.','Together, identify one agreement or question to bring back to the class.']},
restate:{title:'Explain & Restate',steps:['Partner A explains their reasoning. Partner B listens.','Partner B restates: “What I hear you saying is ___.” Partner A confirms or clarifies.','Switch roles.']},
compare:{title:'Compare Approaches',steps:['Each partner explains their approach.','Identify one similarity and one difference.','Discuss why each approach works or where it needs revision.']},
four:{title:'Pair → Group of Four',steps:['Pair: Discuss with a partner. Each person explains an idea using a sentence frame.','Group of four: Join another pair. Each pair contributes one idea from its conversation.','Connect: Identify an agreement, a difference, or a question. Be ready to share it with the class.']}
};
function renderRoutine(){const r=ROUTINES[$('routine').value];$('routinePanel').hidden=!r;$('routineSteps').replaceChildren();if(r){$('routineTitle').textContent=r.title;for(const step of r.steps){const li=document.createElement('li');li.textContent=step;$('routineSteps').append(li)}}}
$('routine').onchange=renderRoutine;renderRoutine();Wild.init();
